setup = {
    'Airplane': {'Stewardess', 'Mechanic', 'First Class Passenger', 'Economy Class Passenger', 'Co-Pilot', 'Captain', 'Air Marshal'},
    'Bank': {'Teller', 'Security Guard', 'Robber', 'Manager', 'Customer', 'Consultant', 'Armored Car Driver'},
    'Beach': {'Thief', 'Lifeguard', 'Kite Surfer', 'Ice Cream Truck Driver', 'Beach Waitress', 'Beach Photographer', 'Beach Goer'},
    'Casino': {'Manager', 'Hustler', 'Head Security Guard', 'Gambler', 'Dealer', 'Bouncer', 'Bartender'},
    'Cathedral': {'Tourist', 'Sponsor', 'Sinner', 'Priest', 'Parishioner', 'Choir Singer', 'Beggar'},
    'Circus tent': {'Visitor', 'Magician', 'Juggler', 'Fire Eater', 'Clown', 'Animal Trainer', 'Acrobat'},
    'Corporate party': {'Unwanted Guest', 'Secretary', 'Owner', 'Manager', 'Entertainer', 'Delivery Boy', 'Accountant'},
    'Crusader army': {'Squire', 'Servant', 'Monk', 'Knight', 'Imprisoned Arab', 'Bishop', 'Archer'},
    'Day spa': {'Beautician', 'Dermatologist', 'Makeup Artist', 'Manicurist', 'Masseuse', 'Stylist', 'Customer'},
    'Embassy': {'Ambassador', 'Diplomat', 'Government Official', 'Refugee', 'Tourist', 'Security Guard', 'Secretary'},
    'Hospital': {'Therapist', 'Surgeon', 'Patient', 'Nurse', 'Intern', 'Doctor', 'Anesthesiologist'},
    'Hotel': {'Security Guard', 'Manager', 'Housekeeper', 'Doorman', 'Customer', 'Bellman', 'Bartender'},
    'Military base': {'Tank Engineer', 'Soldier', 'Sniper', 'Officer', 'Medic', 'Deserter', 'Colonel'},
    'Movie studio': {'Cameraman', 'Costume Artist', 'Producer', 'Sound Engineer', 'Stuntman', 'Director', 'Actor'},
    'Ocean liner': {'Rich Passenger', 'Waiter', 'Musician', 'Mechanic', 'Cook', 'Captain', 'Bartender'},
    'Passenger train': {'Train Driver', 'Stoker', 'Restaurant Chef', 'Passenger', 'Mechanic', 'Engineer', 'Border Patrol'},
    'Pirate ship': {'Slave', 'Sailor', 'Cook', 'Cannoneer', 'Cabin Boy', 'Brave Captain', 'Bound Prisoner'},
    'Polar station': {'Radioman', 'Meteorologist', 'Medic', 'Hydrologist', 'Geologist', 'Expedition Leader', 'Biologist'},
    'Police station': {'Patrol Officer', 'Lawyer', 'Journalist', 'Detective', 'Criminalist', 'Criminal', 'Archivist'},
    'Restaurant': {'Waiter', 'Musician', 'Hostess', 'Head Chef', 'Food Critic', 'Customer', 'Bouncer'},
    'School': {'Gym Teacher', 'Janitor', 'Lunch Lady', 'Maintenance Man', 'Principal', 'Student', 'Security Guard'},
    'Service station': {'Tire Specialist', 'Manager', 'Electrician', 'Car Wash Operator', 'Car Owner', 'Biker', 'Auto Mechanic'},
    'Space station': {'Space Tourist', 'Scientist', 'Pilot', 'Engineer', 'Doctor', 'Commander', 'Alien'},
    'Submarine': {'Sonar Technician', 'Sailor', 'Radioman', 'Navigator', 'Electronics Technician', 'Cook', 'Commander'},
    'Supermarket': {'Butcher', 'Food Sample Demonstrator', 'Janitor', 'Shelf Stocker', 'Security Guard', 'Customer', 'Cashier'},
    'Theater': {'Prompter', 'Director', 'Crewman', 'Coat Check Lady', 'Cashier', 'Audience Member', 'Actor'},
    'University': {'Dean', 'Graduate Student', 'Janitor', 'Maintenance Man', 'Professor', 'Psychologist', 'Student'},
    'World War II Squad': {'Resistance Fighter', 'Radioman', 'Scout', 'Medic', 'Cook', 'Imprisoned Nazi', 'Soldier'}
}
